package br.com.bandtec.projetoindividual;

import java.util.concurrent.ThreadLocalRandom;
/**
 *
 * @author Ritswy
 */
public class App extends javax.swing.JFrame {

    Recurso cpu = new Recurso();
    Recurso memoria = new Recurso();
    Recurso disco = new Recurso();
    
    void sortearValor(Recurso recurso) {
        recurso.dado = ThreadLocalRandom.current()
                .nextDouble(0, recurso.maximoPossivel);
        recurso.porcentagem =(recurso.dado * 100) / recurso.maximoPossivel;
        recurso.somaPorcentagem += recurso.porcentagem;
        recurso.leituras++;
        if(recurso.minimoPorcentagem > recurso.porcentagem) {
            recurso.minimoPorcentagem = recurso.porcentagem;
        }
        if(recurso.maximoPorcentagem < recurso.porcentagem) {
            recurso.maximoPorcentagem = recurso.porcentagem;
        }
    }
    void atualizarTela() {
        //Atualizando valroes de CPU
        lblMainCPU.setText(String.format("%.2f/%.2f %s (%.2f %%)", cpu.dado,
                cpu.maximoPossivel, cpu.medida, cpu.porcentagem));
        pgBarCPU.setValue(cpu.porcentagem.intValue());
        pgBarCPU.setString(String.format("%.2f %% usado",cpu.porcentagem));
        lblUsoPercentCPU.setText(String.format("%.2f %%",cpu.porcentagem));
        lblVelocidadeCPU.setText(String.format("%.2f%s",cpu.dado,cpu.medida));
        lblMinimoCPU.setText(String.format("%.2f %%",cpu.minimoPorcentagem));
        lblMaximoCPU.setText(String.format("%.2f %%",cpu.maximoPorcentagem));
        lblMediaCPU.setText(String.format("%.2f %%",cpu.somaPorcentagem/cpu.leituras));
        
        //Atualizando valores de Disco
        lblMainDisco.setText(String.format("Atividade %.2f %%", disco.porcentagem));
        pgBarDisco.setValue(disco.porcentagem.intValue());
        pgBarDisco.setString(String.format("%.2f %% usado",disco.porcentagem));
        lblUsoDisco.setText(String.format("%.2f %%",disco.porcentagem));
        lblTempoDisco.setText(String.format("%.2f%s",disco.dado,disco.medida));
        lblMinimoDisco.setText(String.format("%.2f %%",disco.minimoPorcentagem));
        lblMaximoDisco.setText(String.format("%.2f %%",disco.maximoPorcentagem));
        lblMediaDisco.setText(String.format("%.2f %%",disco.somaPorcentagem/disco.leituras));
        
        //Atualizando valores de Memoria
        lblMainMemoria.setText(String.format("%.2f/%.2f %s (%.2f %%)", memoria.dado,
                memoria.maximoPossivel, memoria.medida, memoria.porcentagem));
        pgBarMemoria.setValue(memoria.porcentagem.intValue());
        pgBarMemoria.setString(String.format("%.2f %% usado",memoria.porcentagem));
        lblUsoPercentMemoria.setText(String.format("%.2f %%",memoria.porcentagem));
        lblUsoMemoria.setText(String.format("%.2f%s",memoria.dado,memoria.medida));
        lblMinimoMemoria.setText(String.format("%.2f %%",memoria.minimoPorcentagem));
        lblMaximoMemoria.setText(String.format("%.2f %%",memoria.maximoPorcentagem));
        lblMediaMemoria.setText(String.format("%.2f %%",memoria.somaPorcentagem/memoria.leituras));
    }
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        cpu.medida = "GHz";
        memoria.medida = "GB";
        disco.medida = "ms";
        cpu.maximoPossivel = 3.16;
        memoria.maximoPossivel = 2.0;
        //Como a porcentagem de atividade de um disco não é medida exatamente
        //da maneira que to citando aqui, pois pode demorar mais que um tempo
        //maximo, decidi usar dessa forma para manter de maneira didática
        disco.maximoPossivel = 22.4;
        sortearValor(cpu);
        sortearValor(disco);
        sortearValor(memoria);
        atualizarTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        panelMemoria = new javax.swing.JPanel();
        lblTitleMemoria = new javax.swing.JLabel();
        pgBarMemoria = new javax.swing.JProgressBar();
        lblMainMemoria = new javax.swing.JLabel();
        lblTextUsoPercentMemoria = new javax.swing.JLabel();
        lblUsoPercentMemoria = new javax.swing.JLabel();
        lblMinimoMemoria = new javax.swing.JLabel();
        lblTextMinimoMemoria = new javax.swing.JLabel();
        lblTextMaximoMemoria = new javax.swing.JLabel();
        lblMaximoMemoria = new javax.swing.JLabel();
        lblTextMediaMemoria = new javax.swing.JLabel();
        lblMediaMemoria = new javax.swing.JLabel();
        lblTextUsoMemoria = new javax.swing.JLabel();
        lblUsoMemoria = new javax.swing.JLabel();
        panelCPU = new javax.swing.JPanel();
        lblTitleCPU = new javax.swing.JLabel();
        pgBarCPU = new javax.swing.JProgressBar();
        lblMainCPU = new javax.swing.JLabel();
        lblTextUsoPercentCPU = new javax.swing.JLabel();
        lblUsoPercentCPU = new javax.swing.JLabel();
        lblMinimoCPU = new javax.swing.JLabel();
        lblTextMinimoCPU = new javax.swing.JLabel();
        lblTextMaximoCPU = new javax.swing.JLabel();
        lblMaximoCPU = new javax.swing.JLabel();
        lblTextMediaCPU = new javax.swing.JLabel();
        lblMediaCPU = new javax.swing.JLabel();
        lblTextVelocidadeCPU = new javax.swing.JLabel();
        lblVelocidadeCPU = new javax.swing.JLabel();
        panelDisco = new javax.swing.JPanel();
        lblTitleDisco = new javax.swing.JLabel();
        pgBarDisco = new javax.swing.JProgressBar();
        lblMainDisco = new javax.swing.JLabel();
        lblTextUsoDisco = new javax.swing.JLabel();
        lblUsoDisco = new javax.swing.JLabel();
        lblMinimoDisco = new javax.swing.JLabel();
        lblTextMinimoDisco = new javax.swing.JLabel();
        lblTextMaximoDisco = new javax.swing.JLabel();
        lblMaximoDisco = new javax.swing.JLabel();
        lblTextMediaDisco = new javax.swing.JLabel();
        lblMediaDisco = new javax.swing.JLabel();
        lblTextTempoDisco = new javax.swing.JLabel();
        lblTempoDisco = new javax.swing.JLabel();
        btnLeitura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Monitoramento de Hardware");

        lblTitleMemoria.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitleMemoria.setText("Memória");

        pgBarMemoria.setBackground(new java.awt.Color(0, 0, 0));
        pgBarMemoria.setForeground(new java.awt.Color(0, 0, 0));
        pgBarMemoria.setString("00");
        pgBarMemoria.setStringPainted(true);

        lblMainMemoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMainMemoria.setText("00.00/00.00 aaa (000.00)%");

        lblTextUsoPercentMemoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextUsoPercentMemoria.setText("Em uso(%)");

        lblUsoPercentMemoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsoPercentMemoria.setText("000.00 %");

        lblMinimoMemoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMinimoMemoria.setText("000.00 %");

        lblTextMinimoMemoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextMinimoMemoria.setText("Mínimo:");

        lblTextMaximoMemoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextMaximoMemoria.setText("Máximo:");

        lblMaximoMemoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMaximoMemoria.setText("000.00 %");

        lblTextMediaMemoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextMediaMemoria.setText("Média:");

        lblMediaMemoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMediaMemoria.setText("000.00%");

        lblTextUsoMemoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextUsoMemoria.setText("Em uso:");

        lblUsoMemoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsoMemoria.setText("00.00 aaa");

        javax.swing.GroupLayout panelMemoriaLayout = new javax.swing.GroupLayout(panelMemoria);
        panelMemoria.setLayout(panelMemoriaLayout);
        panelMemoriaLayout.setHorizontalGroup(
            panelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMemoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pgBarMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelMemoriaLayout.createSequentialGroup()
                        .addComponent(lblTitleMemoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMainMemoria))
                    .addGroup(panelMemoriaLayout.createSequentialGroup()
                        .addGroup(panelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTextUsoPercentMemoria)
                            .addGroup(panelMemoriaLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblUsoPercentMemoria)))
                        .addGap(18, 18, 18)
                        .addGroup(panelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTextUsoMemoria)
                            .addGroup(panelMemoriaLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblUsoMemoria)))
                        .addGap(126, 126, 126)
                        .addGroup(panelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMemoriaLayout.createSequentialGroup()
                                .addComponent(lblTextMinimoMemoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMinimoMemoria))
                            .addGroup(panelMemoriaLayout.createSequentialGroup()
                                .addComponent(lblTextMediaMemoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMediaMemoria))
                            .addGroup(panelMemoriaLayout.createSequentialGroup()
                                .addComponent(lblTextMaximoMemoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMaximoMemoria)))))
                .addContainerGap())
        );
        panelMemoriaLayout.setVerticalGroup(
            panelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMemoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleMemoria)
                    .addComponent(lblMainMemoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgBarMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextUsoPercentMemoria)
                    .addComponent(lblTextMinimoMemoria)
                    .addComponent(lblMinimoMemoria)
                    .addComponent(lblTextUsoMemoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextMaximoMemoria)
                    .addComponent(lblMaximoMemoria)
                    .addComponent(lblUsoPercentMemoria)
                    .addComponent(lblUsoMemoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextMediaMemoria)
                    .addComponent(lblMediaMemoria))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTitleCPU.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitleCPU.setText("CPU");

        pgBarCPU.setBackground(new java.awt.Color(0, 0, 0));
        pgBarCPU.setForeground(new java.awt.Color(0, 0, 0));
        pgBarCPU.setString("000");
        pgBarCPU.setStringPainted(true);

        lblMainCPU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMainCPU.setText("00.00/00.00 aaa (000.00 %)");

        lblTextUsoPercentCPU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextUsoPercentCPU.setText("Utilização(%):");

        lblUsoPercentCPU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsoPercentCPU.setText("000.00%");

        lblMinimoCPU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMinimoCPU.setText("000.00 %");

        lblTextMinimoCPU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextMinimoCPU.setText("Mínimo:");

        lblTextMaximoCPU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextMaximoCPU.setText("Máximo:");

        lblMaximoCPU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMaximoCPU.setText("000.00%");

        lblTextMediaCPU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextMediaCPU.setText("Média:");

        lblMediaCPU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMediaCPU.setText("000.00%");

        lblTextVelocidadeCPU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextVelocidadeCPU.setText("Velocidade");

        lblVelocidadeCPU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVelocidadeCPU.setText("00.00 aaa");

        javax.swing.GroupLayout panelCPULayout = new javax.swing.GroupLayout(panelCPU);
        panelCPU.setLayout(panelCPULayout);
        panelCPULayout.setHorizontalGroup(
            panelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCPULayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pgBarCPU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelCPULayout.createSequentialGroup()
                        .addComponent(lblTitleCPU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMainCPU))
                    .addGroup(panelCPULayout.createSequentialGroup()
                        .addGroup(panelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTextUsoPercentCPU)
                            .addGroup(panelCPULayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblUsoPercentCPU)))
                        .addGap(18, 18, 18)
                        .addGroup(panelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTextVelocidadeCPU)
                            .addGroup(panelCPULayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblVelocidadeCPU)))
                        .addGap(160, 160, 160)
                        .addGroup(panelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCPULayout.createSequentialGroup()
                                .addComponent(lblTextMinimoCPU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMinimoCPU))
                            .addGroup(panelCPULayout.createSequentialGroup()
                                .addComponent(lblTextMediaCPU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMediaCPU))
                            .addGroup(panelCPULayout.createSequentialGroup()
                                .addComponent(lblTextMaximoCPU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMaximoCPU)))))
                .addContainerGap())
        );
        panelCPULayout.setVerticalGroup(
            panelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCPULayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleCPU)
                    .addComponent(lblMainCPU))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgBarCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCPULayout.createSequentialGroup()
                        .addGroup(panelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTextMinimoCPU)
                            .addComponent(lblMinimoCPU))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTextMaximoCPU)
                            .addComponent(lblMaximoCPU)))
                    .addGroup(panelCPULayout.createSequentialGroup()
                        .addComponent(lblTextUsoPercentCPU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsoPercentCPU))
                    .addGroup(panelCPULayout.createSequentialGroup()
                        .addComponent(lblTextVelocidadeCPU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVelocidadeCPU)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMediaCPU)
                    .addComponent(lblTextMediaCPU))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTitleDisco.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitleDisco.setText("Disco");

        pgBarDisco.setBackground(new java.awt.Color(0, 0, 0));
        pgBarDisco.setForeground(new java.awt.Color(0, 0, 0));
        pgBarDisco.setValue(80);
        pgBarDisco.setString("80% Usado");
        pgBarDisco.setStringPainted(true);

        lblMainDisco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblTextUsoDisco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextUsoDisco.setText("Atividade:");

        lblUsoDisco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblMinimoDisco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblTextMinimoDisco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextMinimoDisco.setText("Mínimo:");

        lblTextMaximoDisco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextMaximoDisco.setText("Máximo:");

        lblMaximoDisco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblTextMediaDisco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextMediaDisco.setText("Média:");

        lblMediaDisco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblTextTempoDisco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextTempoDisco.setText("Tempo de resposta");

        lblTempoDisco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout panelDiscoLayout = new javax.swing.GroupLayout(panelDisco);
        panelDisco.setLayout(panelDiscoLayout);
        panelDiscoLayout.setHorizontalGroup(
            panelDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiscoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pgBarDisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDiscoLayout.createSequentialGroup()
                        .addComponent(lblTitleDisco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMainDisco))
                    .addGroup(panelDiscoLayout.createSequentialGroup()
                        .addGroup(panelDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTextUsoDisco)
                            .addGroup(panelDiscoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblUsoDisco)))
                        .addGap(18, 18, 18)
                        .addGroup(panelDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDiscoLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblTempoDisco))
                            .addComponent(lblTextTempoDisco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDiscoLayout.createSequentialGroup()
                                    .addComponent(lblTextMediaDisco)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblMediaDisco))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDiscoLayout.createSequentialGroup()
                                    .addComponent(lblTextMaximoDisco)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblMaximoDisco)))
                            .addGroup(panelDiscoLayout.createSequentialGroup()
                                .addComponent(lblTextMinimoDisco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMinimoDisco)))))
                .addContainerGap())
        );
        panelDiscoLayout.setVerticalGroup(
            panelDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiscoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleDisco)
                    .addComponent(lblMainDisco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgBarDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextUsoDisco)
                    .addComponent(lblTextMinimoDisco)
                    .addComponent(lblMinimoDisco)
                    .addComponent(lblTextTempoDisco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaximoDisco)
                    .addComponent(lblUsoDisco)
                    .addComponent(lblTempoDisco)
                    .addComponent(lblTextMaximoDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextMediaDisco)
                    .addComponent(lblMediaDisco))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLeitura.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        btnLeitura.setText("Fazer leitura dos dados");
        btnLeitura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeituraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLeitura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCPU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLeitura, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeituraActionPerformed
        sortearValor(cpu);
        sortearValor(memoria);
        sortearValor(disco);
        atualizarTela();
    }//GEN-LAST:event_btnLeituraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.  EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeitura;
    private javax.swing.JLabel lblMainCPU;
    private javax.swing.JLabel lblMainDisco;
    private javax.swing.JLabel lblMainMemoria;
    private javax.swing.JLabel lblMaximoCPU;
    private javax.swing.JLabel lblMaximoDisco;
    private javax.swing.JLabel lblMaximoMemoria;
    private javax.swing.JLabel lblMediaCPU;
    private javax.swing.JLabel lblMediaDisco;
    private javax.swing.JLabel lblMediaMemoria;
    private javax.swing.JLabel lblMinimoCPU;
    private javax.swing.JLabel lblMinimoDisco;
    private javax.swing.JLabel lblMinimoMemoria;
    private javax.swing.JLabel lblTempoDisco;
    private javax.swing.JLabel lblTextMaximoCPU;
    private javax.swing.JLabel lblTextMaximoDisco;
    private javax.swing.JLabel lblTextMaximoMemoria;
    private javax.swing.JLabel lblTextMediaCPU;
    private javax.swing.JLabel lblTextMediaDisco;
    private javax.swing.JLabel lblTextMediaMemoria;
    private javax.swing.JLabel lblTextMinimoCPU;
    private javax.swing.JLabel lblTextMinimoDisco;
    private javax.swing.JLabel lblTextMinimoMemoria;
    private javax.swing.JLabel lblTextTempoDisco;
    private javax.swing.JLabel lblTextUsoDisco;
    private javax.swing.JLabel lblTextUsoMemoria;
    private javax.swing.JLabel lblTextUsoPercentCPU;
    private javax.swing.JLabel lblTextUsoPercentMemoria;
    private javax.swing.JLabel lblTextVelocidadeCPU;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleCPU;
    private javax.swing.JLabel lblTitleDisco;
    private javax.swing.JLabel lblTitleMemoria;
    private javax.swing.JLabel lblUsoDisco;
    private javax.swing.JLabel lblUsoMemoria;
    private javax.swing.JLabel lblUsoPercentCPU;
    private javax.swing.JLabel lblUsoPercentMemoria;
    private javax.swing.JLabel lblVelocidadeCPU;
    private javax.swing.JPanel panelCPU;
    private javax.swing.JPanel panelDisco;
    private javax.swing.JPanel panelMemoria;
    private javax.swing.JProgressBar pgBarCPU;
    private javax.swing.JProgressBar pgBarDisco;
    private javax.swing.JProgressBar pgBarMemoria;
    // End of variables declaration//GEN-END:variables
}
